/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import Evento.Mensaje.EvenMensajeJoptionpane;
import FORMULARIO.BO.BO_item_producto_ingrediente;
import FORMULARIO.BO.BO_producto;
import FORMULARIO.DAO.DAO_item_producto_ingrediente;
import FORMULARIO.DAO.DAO_producto;
import FORMULARIO.ENTIDAD.item_producto_ingrediente;
import FORMULARIO.ENTIDAD.producto;
import FORMULARIO.ENTIDAD.producto_categoria;
import FORMULARIO.ENTIDAD.producto_ingrediente;
import FORMULARIO.ENTIDAD.producto_unidad;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;

/**
 *
 * @author Digno
 */
public class frmtexte extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmtexte
     */
    EvenJFRAME eveJfra = new EvenJFRAME();
    EvenJtable eveJtab = new EvenJtable();
    EvenConexion eveconn = new EvenConexion();
    producto prod = new producto();
    BO_producto pBO = new BO_producto();
    BO_item_producto_ingrediente ipiBO = new BO_item_producto_ingrediente();
    DAO_producto pdao = new DAO_producto();
    DAO_item_producto_ingrediente ipidao = new DAO_item_producto_ingrediente();
    producto_categoria cate = new producto_categoria();
    producto_unidad unid = new producto_unidad();
    producto_ingrediente ingre = new producto_ingrediente();
    item_producto_ingrediente ipingre = new item_producto_ingrediente();
    EvenJTextField evejtf = new EvenJTextField();
    EvenMensajeJoptionpane evmen = new EvenMensajeJoptionpane();
    Connection conn = ConnPostgres.getConnPosgres();
    private boolean isCargado_idcategoria;
    private boolean isCargado_idunidad;
    String v_zona[] = new String[130];
    DefaultListModel model_lista = new DefaultListModel();

    /**
     * Creates new form FrmZonaDelivery
     */
    void abrir_formulario() {
        this.setTitle("PRODUCTO");
        eveJfra.centrar_formulario(this);
        jList_zona.setModel(model_lista);
    }

    void cargar_zona() {
        String titulo = "getdouble_sql_suma";
        String sql = "select (idzona_delivery||'-'||nombre) as nombre from zona_delivery order by 1 desc";
        try {
            ResultSet rs = eveconn.getResulsetSQL(conn, sql, titulo);
            int row = 0;
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                v_zona[row] = nombre;
                row++;
            }
        } catch (Exception e) {
            evmen.mensaje_error(e, sql, titulo);
        }
    }

    void imprimir() {

        for (int i = 0; i < v_zona.length; i++) {
            model_lista.addElement(v_zona[i]);
        }
    }

    void buscar(JTextField txtbuscar) {
        if (!evejtf.getBoo_JTextField_vacio(txtbuscar, "CARGAR UNA BUSQUEDA")) {
            String palabra = txtbuscar.getText();
            model_lista.removeAllElements();
            for (int i = 0; i < v_zona.length; i++) {
                if (v_zona[i] != null) {
                    try {
                        boolean resultado = v_zona[i].toLowerCase().contains(palabra.toLowerCase());
                        if (resultado) {
                            model_lista.addElement(v_zona[i]);
                        }
                    } catch (Exception e) {
                        System.out.println(i + "-ERROR BUSCAR:" + e + " zona:" + v_zona[i]);
                    }
                }
            }
        }
    }

    public frmtexte() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_zona = new javax.swing.JList<>();
        txtbuscar = new javax.swing.JTextField();

        setClosable(true);

        jButton1.setText("cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList_zona);

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargar_zona();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        imprimir();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar(txtbuscar);
        }
    }//GEN-LAST:event_txtbuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList_zona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
